# Autogenerated wrapper script for Draco_jll for x86_64-linux-gnu
export draco_decoder, draco_encoder

JLLWrappers.@generate_wrapper_header("Draco")
JLLWrappers.@declare_executable_product(draco_decoder)
JLLWrappers.@declare_executable_product(draco_encoder)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        draco_decoder,
        "bin/draco_decoder-1.5.6",
    )

    JLLWrappers.@init_executable_product(
        draco_encoder,
        "bin/draco_encoder-1.5.6",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
